### The Basics 

In [1]:
import numpy as np

In [13]:
# create an array with floating point numbers
arr1 = np.array([[1, 2, 3], [0, 1, 2]], float)
arr1

array([[ 1.,  2.,  3.],
       [ 0.,  1.,  2.]])

In [9]:
# array dimensions (number of axes)
arr1.ndim

2

In [10]:
# array shape
arr1.shape

(2, 3)

In [11]:
# array size (total number of elements)
arr1.size

6

In [14]:
# array data type
arr1.dtype

dtype('float64')

In [27]:
# the buffer containing the elements of the array
arr1.data

### Creating Arrays

In [24]:
# create an array of all zeros
np.zeros([3, 4])

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

In [25]:
# create an array of all ones
np.ones([2, 2])

array([[ 1.,  1.],
       [ 1.,  1.]])

In [28]:
# create an uninitialized array, based on current memory
# output may vary
np.empty([3, 2])

array([[ 0.,  0.],
       [ 0.,  0.],
       [ 0.,  0.]])

In [29]:
# create an array using a sequence, similar to normal range() function
np.arange(10, 30, 5)

array([10, 15, 20, 25])

In [30]:
# the numpy arange() function accepts float arguments
np.arange(0, 2, 0.3)

array([ 0. ,  0.3,  0.6,  0.9,  1.2,  1.5,  1.8])

When ```arange``` is used with floating point arguments, it is generally not possible to predict the number of elements obtained, due to the finite floating point precision. For this reason, it is usually better to use the function linspace that receives as an argument the number of elements that we want, instead of the step.

In [33]:
# display 9 numbers between 0 and 2
np.linspace(0, 2, 9)

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

In [43]:
# create an array of 100 points between 0 and 2 pi
x = np.linspace(0, 2 * np.pi, 100)

# take the since of all those numbers
f = np.sin(x)

print(f)

[  0.00000000e+00   6.34239197e-02   1.26592454e-01   1.89251244e-01
   2.51147987e-01   3.12033446e-01   3.71662456e-01   4.29794912e-01
   4.86196736e-01   5.40640817e-01   5.92907929e-01   6.42787610e-01
   6.90079011e-01   7.34591709e-01   7.76146464e-01   8.14575952e-01
   8.49725430e-01   8.81453363e-01   9.09631995e-01   9.34147860e-01
   9.54902241e-01   9.71811568e-01   9.84807753e-01   9.93838464e-01
   9.98867339e-01   9.99874128e-01   9.96854776e-01   9.89821442e-01
   9.78802446e-01   9.63842159e-01   9.45000819e-01   9.22354294e-01
   8.95993774e-01   8.66025404e-01   8.32569855e-01   7.95761841e-01
   7.55749574e-01   7.12694171e-01   6.66769001e-01   6.18158986e-01
   5.67059864e-01   5.13677392e-01   4.58226522e-01   4.00930535e-01
   3.42020143e-01   2.81732557e-01   2.20310533e-01   1.58001396e-01
   9.50560433e-02   3.17279335e-02  -3.17279335e-02  -9.50560433e-02
  -1.58001396e-01  -2.20310533e-01  -2.81732557e-01  -3.42020143e-01
  -4.00930535e-01  -4.58226522e-01

### Basic Operations

In NumPy, arithmetic operators are applied elementwise. A new array is created and filled with the result.

In [47]:
# create two test arrays
a = np.array([x * 10 for x in range(2, 6)])
b = np.arange(4)

In [48]:
# subtract two arrays
c = a - b
print(c)

[20 29 38 47]


In [49]:
# exponentiation
b ** 2

array([0, 1, 4, 9])

In [50]:
# scalar multiplication
10 * np.sin(a)

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

In [51]:
# boolean
a < 35

array([ True,  True, False, False], dtype=bool)

Unlike in many matrix languages, the product operator * operates elementwise in NumPy arrays. The matrix product can be performed using the dot function or method. 

In [52]:
# create two arrays
A = np.array([[1, 2], [3, 4]])
B = np.array([[10, 20], [30, 40]])

In [55]:
# elementwise product
A * B

array([[ 10,  40],
       [ 90, 160]])

In [56]:
# matrix product (inner/dot product)
np.dot(A, B)

array([[ 70, 100],
       [150, 220]])

In [57]:
# another way of calling the dot product is as follows
A.dot(B)

array([[ 70, 100],
       [150, 220]])

In [60]:
# create a random array
a = np.random.random([2, 3])
a

array([[ 0.14568344,  0.08027551,  0.67869978],
       [ 0.41065814,  0.69813645,  0.82318599]])

In [61]:
# sum of all elements
a.sum()

2.8366393059415311

In [62]:
# min or max of all elements
a.min()

0.080275512353508272

By default, these operations apply to the array as though it were a list of numbers, regardless of its shape. However, by specifying the ```axis``` parameter you can apply an operation along the specified axis of an array.

In [64]:
b = np.arange(12).reshape(3, 4)
print(b)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [65]:
# sum b along axis = 0 (each column)
b.sum(axis = 0)

array([12, 15, 18, 21])

In [66]:
# sum b along axis = 1 (each row)
b.sum(axis = 1)

array([ 6, 22, 38])

In [67]:
# cumulative sum along each row
b.cumsum(axis = 1)

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]], dtype=int32)

### Universal Functions