In [92]:
import numpy as np
import pandas as pd

# Merging and Concatenating Data

### Merging Data

In [4]:
# create a DataFrame
df1 = pd.DataFrame({'key':['x', 'z', 'y', 'z', 'x', 'x'],
                    'data_set_1':np.arange(6)})
df1

data_set_1 key
0           0   x
1           1   z
2           2   y
3           3   z
4           4   x
5           5   x

In [5]:
# create another DataFrame
df2 = pd.DataFrame({'key':['q', 'y', 'z'],
                   'data_set_2':[1, 2, 3]})
df2

data_set_2 key
0           1   q
1           2   y
2           3   z

In [7]:
# merge the two DataFrames
pd.merge(df1, df2)

data_set_1 key  data_set_2
0           1   z           3
1           3   z           3
2           2   y           2

This automatically merges DataFrame by an overlapping column. We can also specify the column to merge on.

In [8]:
# merge on a specific column
pd.merge(df1, df2, on='key')

data_set_1 key  data_set_2
0           1   z           3
1           3   z           3
2           2   y           2

We can also specify a how keyword argument, which to use functionality similar to a SQL join. You can set the how keyword to 'left', 'right', 'outer', or 'inner' (default). 

In [9]:
# merge the two DataFrame similar to a left outer join
pd.merge(df1, df2, on='key', how='left')

data_set_1 key  data_set_2
0           0   x         NaN
1           1   z           3
2           2   y           2
3           3   z           3
4           4   x         NaN
5           5   x         NaN

We can also merge data on multiple columns. 

In [16]:
# create a new DataFrame
df3 = pd.DataFrame({'Area':list('111222')
                   ,'Region':list('123123')
                   ,'State':['NY', 'NJ', 'MA', 'CT', 'ME', 'NH']})
df3

Area Region State
0    1      1    NY
1    1      2    NJ
2    1      3    MA
3    2      1    CT
4    2      2    ME
5    2      3    NH

In [19]:
# create another DataFrame
df4 = pd.DataFrame({'Area':list('121212'),
                   'Region':list('112233'),
                   'Manager':['Joe', 'Han', 'Luke', 'Leia', 'Jabba', 'Chewie'],
                   'Sales':[12354, 45874, 8554, 96328, 98745, 14785]})
df4

Area Manager Region  Sales
0    1     Joe      1  12354
1    2     Han      1  45874
2    1    Luke      2   8554
3    2    Leia      2  96328
4    1   Jabba      3  98745
5    2  Chewie      3  14785

In [21]:
# merge df3 and df4 on area and region
pd.merge(df3, df4, on=['Area', 'Region'])

Area Region State Manager  Sales
0    1      1    NY     Joe  12354
1    1      2    NJ    Luke   8554
2    1      3    MA   Jabba  98745
3    2      1    CT     Han  45874
4    2      2    ME    Leia  96328
5    2      3    NH  Chewie  14785

### Merging on an Index

We are able to merge on non-matching column names in different data frames using the left_on and right_on kwargs. Similarly, we can specify to use the left or right index using left_index = True or right_index = True.

In [28]:
# create a new DataFrame
df5 = pd.DataFrame({'Manager':['Joe', 'Han', 'Luke', 'Leia', 'Jabba', 'Chewie'],
                   'Location':['NY', 'NJ', 'MA', 'CT', 'ME', 'NH'],
                   'Phone_Num':[x + random.randint(1111111, 9999999) for x in range(6)]},
                  index = [1234, 5874, 9658, 7412, 2587, 5525])
df5.index.name = 'Store_Nbr'
df5

Location Manager  Phone_Num
Store_Nbr                            
1234            NY     Joe    5205252
5874            NJ     Han    4442418
9658            MA    Luke    2151512
7412            CT    Leia    4185179
2587            ME   Jabba    4053900
5525            NH  Chewie    3299029

In [29]:
# create DataFrame
df6 = pd.DataFrame({'Area':list('11112222'),
                   'Region':list('11221122'),
                   'Store':[1234, 5874, 9658, 8587, 7412, 2587, 9012, 5525]})
df6

Area Region  Store
0    1      1   1234
1    1      1   5874
2    1      2   9658
3    1      2   8587
4    2      1   7412
5    2      1   2587
6    2      2   9012
7    2      2   5525

In [31]:
# merge on the store number (index for df5, column for df6)
pd.merge(df5, df6, left_index = True, right_on = 'Store')

Location Manager  Phone_Num Area Region  Store
0       NY     Joe    5205252    1      1   1234
1       NJ     Han    4442418    1      1   5874
2       MA    Luke    2151512    1      2   9658
4       CT    Leia    4185179    2      1   7412
5       ME   Jabba    4053900    2      1   2587
7       NH  Chewie    3299029    2      2   5525

If we have matching columns or index names across the two data frames to join, we can use the .join() method. 

In [63]:
# re-create df6 with a named index
df7 = pd.DataFrame({'Area':list('11112222'),
                   'Region':list('11221122')},
                   index = [1234, 5874, 9658, 8587, 7412, 2587, 9012, 5525])
df7

Area Region
1234    1      1
5874    1      1
9658    1      2
8587    1      2
7412    2      1
2587    2      1
9012    2      2
5525    2      2

In [67]:
# left outer join df7 and df5
df7.join(df5)

Area Region Location Manager  Phone_Num
1234    1      1       NY     Joe    5205252
5874    1      1       NJ     Han    4442418
9658    1      2       MA    Luke    2151512
8587    1      2      NaN     NaN        NaN
7412    2      1       CT    Leia    4185179
2587    2      1       ME   Jabba    4053900
9012    2      2      NaN     NaN        NaN
5525    2      2       NH  Chewie    3299029

In [69]:
# inner join df7 and df5
df7.join(df5, how='inner')

Area Region Location Manager  Phone_Num
1234    1      1       NY     Joe    5205252
5874    1      1       NJ     Han    4442418
9658    1      2       MA    Luke    2151512
7412    2      1       CT    Leia    4185179
2587    2      1       ME   Jabba    4053900
5525    2      2       NH  Chewie    3299029

### Concatenating Data

In [72]:
# create a numpy matrix
arr1 = np.arange(9).reshape(3, 3)
arr1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [75]:
# concatenate the matrix with itself
# use default axis (= 0)
np.concatenate([arr1, arr1])

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8],
       [0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [76]:
# concatenate a matrix with itself using axis = 1
np.concatenate([arr1, arr1], axis = 1)

array([[0, 1, 2, 0, 1, 2],
       [3, 4, 5, 3, 4, 5],
       [6, 7, 8, 6, 7, 8]])

In [81]:
# create a series
ser1 = pd.Series([0, 1, 2], index = ['t', 'u', 'v'])
ser1

t    0
u    1
v    2
dtype: int64

In [82]:
# create another series
ser2 = pd.Series([3, 4], index = ['x', 'y']) 
ser2

x    3
y    4
dtype: int64

In [84]:
# concatenate the two series using the default axis = 0
pd.concat([ser1, ser2])

t    0
u    1
v    2
x    3
y    4
dtype: int64

In [85]:
# concatenate the series using axis = 1
pd.concat([ser1, ser2], axis = 1)

0   1
t   0 NaN
u   1 NaN
v   2 NaN
x NaN   3
y NaN   4

In [86]:
# concatenate the series with a multiple index
pd.concat([ser1, ser2], keys = ['cat1', 'cat2'])

cat1  t    0
      u    1
      v    2
cat2  x    3
      y    4
dtype: int64

In [87]:
# create a data frame
df8 = pd.DataFrame(np.random.randn(4, 3), columns = ['x,', 'y', 'z'])
df8

x,         y         z
0 -0.380100 -0.377894 -0.530915
1 -0.973896  0.054420  1.682353
2 -1.031988  0.149943 -0.075304
3 -1.417644 -0.164817  0.030552

In [89]:
# create another data frame
df9 = pd.DataFrame(np.random.randn(3, 3), columns = ['y', 'q', 'x'])
df9

y         q         x
0  0.246828 -0.110602  0.416604
1 -0.398457 -0.394958  0.582773
2 -0.174193 -0.970128 -1.495251

In [90]:
# concatenate the data frames
pd.concat([df8, df9])

q         x        x,         y         z
0       NaN       NaN -0.380100 -0.377894 -0.530915
1       NaN       NaN -0.973896  0.054420  1.682353
2       NaN       NaN -1.031988  0.149943 -0.075304
3       NaN       NaN -1.417644 -0.164817  0.030552
0 -0.110602  0.416604       NaN  0.246828       NaN
1 -0.394958  0.582773       NaN -0.398457       NaN
2 -0.970128 -1.495251       NaN -0.174193       NaN

In [91]:
# concatenate the data frames with a new index
pd.concat([df8, df9], ignore_index = True)

q         x        x,         y         z
0       NaN       NaN -0.380100 -0.377894 -0.530915
1       NaN       NaN -0.973896  0.054420  1.682353
2       NaN       NaN -1.031988  0.149943 -0.075304
3       NaN       NaN -1.417644 -0.164817  0.030552
4 -0.110602  0.416604       NaN  0.246828       NaN
5 -0.394958  0.582773       NaN -0.398457       NaN
6 -0.970128 -1.495251       NaN -0.174193       NaN

### Combining DataFrames

In [95]:
# create series
ser3 = pd.Series([2, np.nan, 4, np.nan, 6, np.nan], 
        index = ['q', 'r', 's', 't', 'u', 'v'])
ser3

q     2
r   NaN
s     4
t   NaN
u     6
v   NaN
dtype: float64

In [99]:
# create another series
ser4 = pd.Series(np.arange(len(ser3)), dtype=np.float64,
                 index = ['q', 'r', 's', 't', 'u', 'v'])
ser4

q    0
r    1
s    2
t    3
u    4
v    5
dtype: float64

In [103]:
# create a combined series, where we take the value from ser3 if it exists
# else take the value from ser4

pd.Series(np.where(pd.isnull(ser3), ser4, ser3), index = ser3.index)

q    2
r    1
s    4
t    3
u    6
v    5
dtype: float64

In [105]:
# shortcut to do the same thing in pandas using .combine_first()
ser3.combine_first(ser4)

q    2
r    1
s    4
t    3
u    6
v    5
dtype: float64

In [106]:
# create data frame of odd values
nil = np.nan
df_odds = pd.DataFrame({'x':[1., nil, 3., nil],
                        'y':[nil, 5., nil, 7.],
                        'z':[nil, 9., nil, 11.]})
df_odds

x   y   z
0   1 NaN NaN
1 NaN   5   9
2   3 NaN NaN
3 NaN   7  11

In [107]:
# create a data frame with even values
df_evens = pd.DataFrame({'x':[2., 4., nil, 6., 8.],
                        'y':[nil, 10., 12., 14., 16.]})
df_evens

x   y
0   2 NaN
1   4  10
2 NaN  12
3   6  14
4   8  16

In [108]:
# combine these data frames
df_odds.combine_first(df_evens)

x   y   z
0  1 NaN NaN
1  4   5   9
2  3  12 NaN
3  6   7  11
4  8  16 NaN

What does this do? Remember, it takes each value of df_odds, and if it has a value, it uses it. If the value from df_odds is missing, it uses the value from df_evens.